
basen_bms:
  - address: ${basen_bms_address}
    id: ${basen_bms_id}
    update_interval: 5s
    
# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

binary_sensor:
  - platform: basen_bms
    basen_bms_id: ${basen_bms_id}
    connected:
      name: "${name} Connected"

sensor:
  - platform: basen_bms
    basen_bms_id: ${basen_bms_id}
    voltage:
      name: "${name} voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    state_of_charge:
      name: "${name} state of charge"
    state_of_health:
      name: "${name} state of health"
    capacity:
      name: "${name} capacity"
    cycles:
      name: "${name} cycles"
    temperature1:
      name: "${name} temperature"
    temperature2:
      name: "${name} temperature 2"
    temperature3:
      name: "${name} temperature 3"
    temperature4: 
      name: "${name} temperature 4"
    temperature_mos:
      name: "${name} temperature mos"
    temperature_ambient:
      name: "${name} temperature ambient"
    avg_cell_voltage:
      name: "${name} average cell voltage"
    min_cell_voltage:
      name: "${name} minimum cell voltage"
    max_cell_voltage:
      name: "${name} maximum cell voltage"
    min_cell_index:
      name: "${name} minimum cell index"
    max_cell_index:
      name: "${name} maximum cell index"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    cell_voltage_01:
      name: "${name} cell voltage 01"
    cell_voltage_02:
      name: "${name} cell voltage 02"
    cell_voltage_03:
      name: "${name} cell voltage 03"
    cell_voltage_04:
      name: "${name} cell voltage 04"
    cell_voltage_05:
      name: "${name} cell voltage 05"
    cell_voltage_06:
      name: "${name} cell voltage 06"
    cell_voltage_07:
      name: "${name} cell voltage 07"
    cell_voltage_08:
      name: "${name} cell voltage 08"
    cell_voltage_09:
      name: "${name} cell voltage 09"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
      name: "${name} cell voltage 12"
    cell_voltage_13:
      name: "${name} cell voltage 13"
    cell_voltage_14:
      name: "${name} cell voltage 14"
    cell_voltage_15:
      name: "${name} cell voltage 15"
    cell_voltage_16:
      name: "${name} cell voltage 16"

text_sensor:
 - platform: basen_bms
   basen_bms_id: ${basen_bms_id}
   bms_version:
     name: "${name} BMS version"
   barcode:
     name: "${name} BMS barcode"
   status_bitmask:
     name: "${name} Status bitmap"
   status:
     name: "${name} Status"
 